import { exportPack } from "../src/export";
import { importPack } from "../src/import";
import { mkdirSync, writeFileSync, readFileSync } from "fs";
import { Glob } from "bun";

// --- MOCKED ZO CORE TOOLS ---

function list_space_routes(): string[] {
  const glob = new Glob("./examples/routes/**/*.{ts,tsx}");
  return Array.from(glob.scanSync()).map(file => {
    const normalized = file.replaceAll("\\", "/");
    const prefix = "./examples/routes";
    let p = normalized.startsWith(prefix) ? normalized.slice(prefix.length) : normalized;
    p = p.replace(/\.tsx?$/, "");
    if (p === "/index") return "/";
    return p;
  });
}

function get_space_route(path: string): { route_type: "api" | "page"; public: boolean; code: string } {
  const isApi = path.startsWith("/api/");
  const fileSuffix = isApi ? `${path}.ts` : (path === "/" ? "/index.tsx" : `${path}.tsx`);
  const fullPath = `./examples/routes${fileSuffix}`;
  
  return {
    route_type: isApi ? "api" : "page",
    public: true,
    code: readFileSync(fullPath, "utf-8"),
  };
}

function update_space_route(path: string, route_type: "api" | "page", code: string, isPublic: boolean) {
  console.log(`[Zo Substrate] Deploying ${route_type} route: ${path} (Public: ${isPublic})`);
  const fileSuffix = route_type === "api" ? `${path}.ts` : (path === "/" ? "/index.tsx" : `${path}.tsx`);
  const fullPath = `./examples/routes${fileSuffix}`;
  
  // Ensure directory exists
  const dir = fullPath.replaceAll("\\", "/").split("/").slice(0, -1).join("/");
  if (dir) {
    mkdirSync(dir, { recursive: true });
  }
  writeFileSync(fullPath, code);
}

// --- EMULATED AGENT LOOP ---

async function emulateExport() {
  console.log("🎬 --- EMULATING AGENT EXPORT LOOP ---");
  
  // 1. Discover routes (Simulates list_space_routes)
  const routes = list_space_routes();
  console.log(`Found live routes: ${routes.join(", ")}`);
  
  // 2. Fetch code (Simulates get_space_route)
  const routeData = routes.map(r => ({
    path: r,
    ...get_space_route(r),
  }));
  
  // 3. Delegate packaging to CLI
  console.log("Delegating packaging to Zopack Export...");
  const outputPath = await exportPack({
    name: "emulated-pack",
    description: "An emulated package generated by mock Zo Core Tools",
    output: "examples/emulated-pack.zopack.md",
  }, routeData);
  
  console.log(`✅ Zopack successfully generated at: ${outputPath}\n`);
}

async function emulateImport() {
  console.log("🎬 --- EMULATING AGENT IMPORT & DEPLOY LOOP ---");
  
  // 1. Ingest package via CLI (Simulates bun import.ts --file ... --preview)
  console.log("Parsing package...");
  const plan = await importPack({
    file: "examples/emulated-pack.zopack.md",
    handle: "ethan",
  });
  
  if (!plan) {
    console.error("Failed to parse plan.");
    return;
  }
  
  // 2. Security Scan (Static Analysis of Plan)
  console.log("Performing Security Scan on route codes...");
  for (const route of plan.routes) {
    if (route.code.includes("eval(") || route.code.includes("process.env")) {
      console.warn(`⚠️ Security warning: Suspicious pattern found in ${route.path}!`);
    }
  }
  
  // 3. Install dependencies & directories
  console.log(`Installing npm dependencies: ${plan.npm_deps.join(", ") || "none"}`);
  console.log(`Creating required directories: ${plan.directories.join(", ") || "none"}`);
  
  // 4. Inject routes back to Substrate (Simulates update_space_route)
  for (const route of plan.routes) {
    update_space_route(route.path, route.route_type, route.code, route.public);
  }
  
  console.log("✅ Emulated Deployment complete!\n");
}

async function main() {
  await emulateExport();
  await emulateImport();
}

main().catch(err => {
  console.error("Emulation failed:", err);
});
