import { exportPack } from "../src/export";
import { importPack } from "../src/import";
import { createPackManifest } from "../src/pack-manifest";
import { materializeSetupWorkspace } from "../src/setup-workspace";
import { buildClientBundles } from "../src/serve";
import { readFileSync } from "fs";
import { join } from "path";
import { registerZopackPlugin, setActivePack, setWorkspaceRoot } from "../src/zopack-plugin";

async function emulateExport() {
  console.log("🎬 --- EMULATING AGENT EXPORT LOOP ---");

  const routeData = JSON.parse(readFileSync("examples/routes.json", "utf-8"));

  console.log("Delegating packaging to Zopack Export...");
  const outputPath = await exportPack(
    {
      name: "emulated-pack",
      description: "An emulated package generated by mock Zo Core Tools",
      output: "examples/emulated-pack.zopack.md",
    },
    routeData,
  );

  console.log(`✅ Zopack successfully generated at: ${outputPath}\n`);
}

async function emulateImport() {
  console.log("🎬 --- EMULATING AGENT IMPORT & SERVE LOOP ---");

  console.log("Parsing package...");
  const plan = await importPack({
    file: "examples/emulated-pack.zopack.md",
    handle: "ethan",
  });

  if (!plan) {
    console.error("Failed to parse plan.");
    return;
  }

  console.log("Performing Security Scan on route codes...");
  for (const route of plan.routes) {
    if (route.code.includes("eval(") || route.code.includes("process.env")) {
      console.warn(`⚠️ Security warning: Suspicious pattern found in ${route.path}!`);
    }
  }

  console.log(`Installing npm dependencies: ${plan.npm_deps.join(", ") || "none"}`);
  console.log(`Creating required directories: ${plan.directories.join(", ") || "none"}`);

  registerZopackPlugin();
  setActivePack(plan);
  const workspaceDir = materializeSetupWorkspace(plan);
  setWorkspaceRoot(workspaceDir);

  const packFile = join(process.cwd(), "examples/emulated-pack.zopack.md");
  const manifest = createPackManifest(plan, packFile);
  const buildDir = join(process.cwd(), ".zopack-build", "emulate-test");
  const bundles = await buildClientBundles(manifest, buildDir);

  console.log(`Built ${bundles.size} page bundle(s) from pack without writing routes/`);
  console.log("✅ Emulated pack serve preparation complete!\n");
}

async function main() {
  await emulateExport();
  await emulateImport();
}

main().catch((err) => {
  console.error("Emulation failed:", err);
});
